VERSION 0.8
FROM python:3.10-slim

build:
    COPY ./dist/bin /app.bin

    ENTRYPOINT /app.bin

    SAVE IMAGE cli

    ARG TARGETARCH
    SAVE IMAGE --push chrismatic/uv-earthly-mono-example:cli_$TARGETARCH
