VERSION 0.8
# No need for a python image as we bundle it in the binary
FROM debian:bookworm-slim

build:
    COPY ./dist/bin /app.bin

    ENTRYPOINT /app.bin

    SAVE IMAGE server

    ARG TARGETARCH
    SAVE IMAGE --push chrismatic/uv-earthly-mono-example:server_$TARGETARCH
