VERSION 0.8
FROM python:3.10-slim

build:
    COPY ./dist/bin /app.bin

    ENTRYPOINT /app.bin

    SAVE IMAGE server

    # USERARCH ?
    ARG TARGETARCH
    SAVE IMAGE --push chrismatic/uv-earthly-mono-example:server_$TARGETARCH
