name: Build

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.15

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: chrismatic
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install dependencies
        run: uv sync && uv tool install pex

      - name: Run tests
        run: make test

      - name: Build and push images
        run: EARTHLY_PUSH=true make build-images
